### PR TITLE
Add support for dynamic pyhton scripts as input for Ansible Inventory and Ansible Vault files.

### PR DESCRIPTION
**Pull request by stefanseifert**

### CODE REVIEW

**Comment by tobias-richter** [comment]
@stefanseifert i can confirm that this is working.
The Problem is, that the ec2 json inventory script per default returns the public ip adresses and we need for example the internal IP address to allow dispatcher flushes.

Stripped down and example inventory with fake ip adresses:
```
{
    "_meta": {
        "hostvars": {
            "192.168.100.1": {
                "ansible_host": "192.168.10.1", 
                "ec2_private_ip_address": "127.0.100.1", 
                "ec2_public_dns_name": "ec2-127-0-100-1.eu-west-1.compute.amazonaws.com", 
                "ec2_tag_Env": "dev", 
                "ec2_tag_Name": "dev_aem", 
                "ec2_tag_Project": "pvrnd-cma", 
                "ec2_tag_Role": "aem", 
                "ec2_tag_conga_nodes": [
                    "author-dev.website1.com", 
                    "dev.website1.com"
                ], 
                "ec2_tag_conga_roles": [
                    "aem-cms", 
                    "aem-dispatcher"
                ], 
                "ec2_tag_conga_variant_node_mapping": [
                    "aem-author=author-dev.website1.com", 
                    "aem-publish=dev.website1.com"
                ], 
                "ec2_tag_conga_variants": [
                    "aem-author", 
                    "aem-publish"
                ], 
            }
        }
    }, 
    "tag_Name_dev_aem": [
        "192.168.100.1"
    ], 
}
```
With the current implementation we are only able to get the external IP address
```
httpd:
    accessRestriction:
      dispatcherFlushFromIp: 127.0.0.1 ${ansible-inventory::tag_Name_dev_aem}
```

What we need would be something like:
```
httpd:
    accessRestriction:
      dispatcherFlushFromIp: 127.0.0.1 ${ansible-inventory::tag_Name_dev_aem::ec2_private_ip_address}
```

But here we have to think about the ini inventory hostfiles where the group/hostvars are calculated by ansible. One option would be to only allow host/group vars that are present in the inventory file and ignore the hostvars from the host_vars folder.

**Comment by stefanseifert** [comment]
ah - but what you describe is a completely different problem - so we need to enhance the way to parse the information from the inventory JSON data. this PR is only about fetching inventory data via dynamic pyhton script. if this works basically we can merge this PR.

**Comment by tobias-richter** [comment]
@stefanseifert in that case you have my +1

**Comment by tobias-richter** [comment]
This PR was manually merged.

**Pull request closed without merging**
